services:
  database:
    image: 'postgres:latest'
    container_name: database
    restart: always
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'UIS'
      POSTGRES_DB: bank24017
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./:/code
    environment:
      - PGPASSWORD='UIS'
      - HOST=database
    ports:
      - "5000:5000" 
    links:
      - database
